# Generated by Django 2.1.5 on 2019-08-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millas', models.DecimalField(decimal_places=2, max_digits=2)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='gmaps.Ubicacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origen', to='gmaps.Ubicacion')),
            ],
        ),
    ]
