# Generated by Django 2.1.5 on 2019-08-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0002_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='millas',
            field=models.IntegerField(),
        ),
    ]
