# Generated by Django 2.1.5 on 2019-08-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps', '0003_auto_20190811_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='millas',
            new_name='metros',
        ),
    ]
